<?php

if(empty($data["service_provider"])) {
    $data["service_provider"] = WHMCS\Mail\MailAuthHandler::PROVIDER_GENERIC;
}
echo "\n<script>\n    jQuery(document).ready(function() {\n        var authFields = {\n            '";
echo WHMCS\Mail\MailAuthHandler::AUTH_TYPE_PLAIN;
echo "': [\n                'password'\n            ],\n            '";
echo WHMCS\Mail\MailAuthHandler::AUTH_TYPE_OAUTH2;
echo "': [\n                'oauth2_callback_url',\n                'oauth2_client_id',\n                'oauth2_client_secret',\n                'oauth2_refresh_token'\n            ]\n        };\n\n        var legacyMailProtocolFields = [\n            'host',\n            'port',\n            'login'\n        ];\n\n        var legacyMailProtocolSupportMap = ";
echo json_encode(WHMCS\Mail\MailAuthHandler::getProviderLegacyMailProtocolSupportMap());
echo ";\n        var authTypeMap = ";
echo json_encode(WHMCS\Mail\MailAuthHandler::getProviderAuthTypeMap());
echo ";\n\n        var csrfToken = '";
echo generate_token("plain");
echo "';\n\n        var serviceProviderPopHosts = ";
echo json_encode(WHMCS\Mail\MailAuthHandler::PROVIDER_POP_HOSTS);
echo ";\n        var serviceProviderPopPorts = ";
echo json_encode(WHMCS\Mail\MailAuthHandler::PROVIDER_POP_PORTS);
echo ";\n\n        var findConfigField = function (fieldName) {\n            return jQuery('#frmDepartmentConfiguration')\n                .find('input[name=\"' + fieldName + '\"],select[name=\"' + fieldName + '\"]')\n                .first();\n        };\n\n        var successDiv = jQuery('#mailProviderTestSuccess');\n        var errorDiv = jQuery('#mailProviderError');\n\n        var refreshTokenField = findConfigField('oauth2_refresh_token');\n        var authTypeSelect = findConfigField('auth_type');\n        var serviceProviderField = findConfigField('service_provider');\n\n        var forceAuthType = null;\n        var defaultAuthType = null;\n\n        var currentServiceProvider;\n\n        authTypeSelect.attr('id', 'popAuthTypeSelect');\n\n        var displayField = function(field, display) {\n            var settingRow = jQuery(field).parents('tr');\n\n            if (display) {\n                settingRow.show();\n            } else {\n                settingRow.hide();\n            }\n\n            jQuery(settingRow).find('[data-generic-field-label]').each(function() {\n                var label = this;\n                var genericText = jQuery(label).data('generic-field-label');\n\n                var providerSpecificLabel = jQuery(label).data((currentServiceProvider.toLowerCase()) + '-field-label');\n\n                jQuery(label).text(providerSpecificLabel || genericText);\n            });\n        };\n\n        var applyServiceProviderSelection = function(newServiceProvider) {\n            currentServiceProvider = newServiceProvider;\n\n            jQuery(serviceProviderField).val(newServiceProvider);\n\n            var supportedAuthTypes = authTypeMap[newServiceProvider];\n\n            var legacyMailProtocolsSupported = legacyMailProtocolSupportMap[newServiceProvider];\n\n            legacyMailProtocolFields.forEach(function (field) {\n                displayField(findConfigField(field), legacyMailProtocolsSupported);\n            });\n\n            defaultAuthType = supportedAuthTypes[0];\n\n            if (supportedAuthTypes.length === 1) {\n                forceAuthType = defaultAuthType;\n            } else {\n                forceAuthType = null;\n            }\n\n            applyAuthTypeSelect();\n\n            var popPortField = findConfigField('port');\n\n            if (!popPortField.val()) {\n                var popPortValue = serviceProviderPopPorts[newServiceProvider];\n\n                popPortField.val(popPortValue);\n            }\n\n            var popHostField = findConfigField('host');\n\n            var updateHost;\n\n            var newHostValue = newServiceProvider === '";
echo WHMCS\Mail\MailAuthHandler::PROVIDER_GENERIC;
echo "'\n                ? ''\n                : serviceProviderPopHosts[newServiceProvider];\n\n            if (!popHostField.val()) {\n                updateHost = true;\n            } else {\n                if (popHostField.val() === popHostField.data('default-value')) {\n                    updateHost = true;\n                }\n            }\n\n            if (updateHost) {\n                popHostField\n                    .val(newHostValue)\n                    .data('default-value', newHostValue);\n            }\n\n            jQuery('[data-role=\"oauth-provider-instructions\"]').hide();\n            jQuery('[data-role=\"oauth-provider-instructions\"][data-provider=\"' + newServiceProvider + '\"').show();\n        };\n\n        var applyAuthTypeSelect = function() {\n            var currentAuthType;\n\n            if (forceAuthType) {\n                currentAuthType = forceAuthType;\n                jQuery(authTypeSelect).val(currentAuthType);\n                displayField(authTypeSelect, false);\n            } else {\n                currentAuthType = jQuery(authTypeSelect).val();\n                displayField(authTypeSelect, true);\n            }\n\n            if (currentAuthType && authFields[currentAuthType]) {\n                Object.keys(authFields).forEach(function (authType) {\n                    authFields[authType].forEach(function (field) {\n                        displayField(\n                            findConfigField(field),\n                            authType === currentAuthType\n                        );\n                    });\n                });\n            }\n\n            jQuery('[data-role=\"auth-type-element\"]').hide();\n            jQuery('[data-role=\"auth-type-element\"][data-auth-type=\"' + currentAuthType + '\"]').show();\n\n            if (currentAuthType === '";
echo WHMCS\Mail\MailAuthHandler::AUTH_TYPE_OAUTH2;
echo "') {\n                if (!jQuery(refreshTokenField).val()) {\n                    jQuery('#btnTestMailConnection').attr('disabled', 'disabled');\n                }\n\n                jQuery('#colMailSetup')\n                    .removeClass('col-lg-12')\n                    .addClass('col-md-8 col-lg-9');\n\n                jQuery('#colOauthHelp').show();\n            } else {\n                jQuery('#btnTestMailConnection').removeAttr('disabled');\n\n                jQuery('#colMailSetup')\n                    .removeClass('col-md-8 col-lg-9')\n                    .addClass('col-lg-12');\n\n                jQuery('#colOauthHelp').hide();\n            }\n\n            if (jQuery('#smtpOauth2CallbackUrl').is(':visible')) {\n                var error = '';\n\n                if (";
echo (int) (!App::getSystemURL());
echo ") {\n                    error = '";
echo AdminLang::trans("mail.error.systemUrlMissing");
echo "';\n                } else if (\n                    jQuery(serviceProviderField).val() === '";
echo WHMCS\Mail\MailAuthHandler::PROVIDER_MICROSOFT;
echo "'\n                    && ";
echo (int) (!WHMCS\Mail\Providers\Microsoft\MicrosoftGraphMailClient::isUrlRewriteModeValid());
echo "                ) {\n                    error = '";
echo AdminLang::trans("mail.error.friendlyUrlModeInvalid");
echo "';\n                }\n\n                if (error) {\n                    errorDiv.text(error).slideDown();\n                } else {\n                    jQuery(errorDiv).slideUp();\n                }\n            } else {\n                jQuery(errorDiv).slideUp();\n            }\n        };\n\n        applyServiceProviderSelection('";
echo $data["service_provider"];
echo "');\n        applyAuthTypeSelect();\n\n        jQuery(document).on(\n            'click',\n            'a[data-role=\"provider-switch\"]',\n            function(e) {\n                e.preventDefault();\n\n                let newServiceProvider = jQuery(this).data('provider')\n                let defaultAuthType = authTypeMap[newServiceProvider][0];\n                jQuery('#providerSelectGroup').find('li[role=\"presentation\"]').removeClass('active');\n                jQuery(this).parent('li[role=\"presentation\"]').addClass('active');\n                jQuery(authTypeSelect).val(defaultAuthType);\n                applyServiceProviderSelection(newServiceProvider);\n\n                return false;\n            }\n        );\n\n        jQuery(document).off('change', '#popAuthTypeSelect');\n        jQuery(document).on('change', '#popAuthTypeSelect', applyAuthTypeSelect);\n\n        jQuery(document).off('click', '#btnConfigureOauth2');\n        jQuery(document).on('click', '#btnConfigureOauth2', function() {\n            var self = jQuery(this);\n\n            self.addClass('disabled').prop('disabled', true);\n\n            jQuery(successDiv).slideUp();\n            jQuery(errorDiv).slideUp();\n\n            WHMCS.http.jqClient.jsonPost(\n                {\n                    url: '";
echo routePath("admin-setup-support-oauth2-get-auth-url");
echo "',\n                    data: {\n                        target: 'SupportDepartment',\n                        serviceProvider: jQuery(serviceProviderField).val(),\n                        supportDepartmentId: ";
echo $data["departmentId"] ?? 0;
echo ",\n                        serviceProvider: findConfigField('service_provider').val(),\n                        clientId: findConfigField('oauth2_client_id').val(),\n                        clientSecret: findConfigField('oauth2_client_secret').val(),\n                        token: csrfToken\n                    },\n                    success: function(data) {\n                        var popupOptions = {\n                            width: 500,\n                            height: 700\n                        };\n\n                        popupOptions.left = Math.round((screen.availWidth - popupOptions.width) / 2);\n                        popupOptions.top = Math.round((screen.availHeight - popupOptions.height) / 2);\n\n                        var optionsString = Object.keys(popupOptions).map(function (item) {\n                            return item + '=' + popupOptions[item];\n                        }).join(',');\n\n                        window.open(data.url, 'mailOauth2Popup', optionsString);\n\n                    },\n                    error: function(error) {\n                        errorDiv.text(error).slideDown();\n                    },\n                    fail: function(error, xhr) {\n                        errorDiv.text(xhr.responseJSON.errorMessage).slideDown();\n                    },\n                    always: function() {\n                        self.removeClass('disabled').prop('disabled', false);\n                    }\n                }\n            );\n        });\n\n        jQuery(document).on('click', '#btnTestMailConnection', function() {\n            var self = jQuery(this);\n            var spinner = jQuery(self).find('i');\n            var text = jQuery(self).find('span');\n\n            self.addClass('disabled').prop('disabled', true);\n            jQuery(text).text('";
echo AdminLang::trans("supportticketdepts.pop3connectiontestinprogress");
echo "')\n\n            jQuery(successDiv).slideUp();\n            jQuery(errorDiv).slideUp();\n            jQuery(spinner).show();\n            jQuery('.infobox:first').slideUp();\n\n            WHMCS.http.jqClient.jsonPost(\n                {\n                    url: '";
echo routePath("admin-setup-support-test-mail-connection");
echo "',\n                    data: jQuery('#frmDepartmentConfiguration').serialize(),\n                    success: function(data) {\n                        jQuery(successDiv)\n                            .text('";
echo AdminLang::trans("supportticketdepts.pop3testconnectionsuccess");
echo "')\n                            .slideDown();\n                    },\n                    error: function(error) {\n                        errorDiv\n                            .text('";
echo AdminLang::trans("supportticketdepts.pop3testconnectionerror");
echo "' + ': ' + error)\n                            .slideDown();\n                    },\n                    fail: function(error, xhr) {\n                        errorDiv\n                            .text('";
echo AdminLang::trans("supportticketdepts.pop3testconnectionerror");
echo "' + ': ' + xhr.responseJSON.errorMessage)\n                            .slideDown();\n                    },\n                    always: function() {\n                        jQuery(spinner).hide();\n                        jQuery(text).text('";
echo AdminLang::trans("supportticketdepts.pop3testconfiguration");
echo "')\n                        self.removeClass('disabled').prop('disabled', false);\n                    }\n                }\n            );\n        });\n\n        window.whmcsSetOauthRefreshToken = function(refreshToken) {\n            refreshTokenField.val(refreshToken);\n\n            jQuery(successDiv)\n                .text('";
echo AdminLang::trans("mail.connectionTokenSuccess");
echo "')\n                .slideDown();\n\n            jQuery('#btnTestMailConnection').removeAttr('disabled');\n        };\n    });\n</script>\n\n<p style=\"text-align:left;\"><b>";
echo AdminLang::trans("supportticketdepts.pop3importconfigtitle");
echo "</b>\n    ";
echo AdminLang::trans("supportticketdepts.pop3importconfigdesc");
echo "</p>\n\n<div class=\"alert alert-success\" id=\"mailProviderTestSuccess\" style=\"display: none;\" role=\"alert\"></div>\n<div class=\"alert alert-warning\" id=\"mailProviderError\" style=\"display: none;\" role=\"alert\"></div>\n\n<div class=\"row\">\n    <div class=\"col-md-8 col-lg-9\" id=\"colMailSetup\">\n        <table class=\"form\" width=\"100%\" border=\"0\" cellspacing=\"2\" cellpadding=\"3\">\n            <tr>\n                <td width=\"175px\" class=\"fieldlabel\">";
echo AdminLang::trans("mail.provider");
echo "</td>\n                <td class=\"fieldarea\">\n                    <input type=\"hidden\" name=\"service_provider\" value=\"";
echo $data["service_provider"];
echo "\">\n                    <ul id=\"providerSelectGroup\" class=\"nav nav-pills slim\">\n                        ";
$providers = array_merge([WHMCS\Mail\MailAuthHandler::PROVIDER_GENERIC], array_keys(WHMCS\Mail\MailAuthHandler::PROVIDER_CLASSES));
echo "                        ";
foreach ($providers as $providerName) {
    echo "                            <li role=\"presentation\" ";
    echo $providerName === $data["service_provider"] ? "class=\"active" : "";
    echo "\">\n                            <a href=\"#\" data-role=\"provider-switch\" data-provider=\"";
    echo $providerName;
    echo "\">\n                                ";
    echo $providerName === WHMCS\Mail\MailAuthHandler::PROVIDER_GENERIC ? AdminLang::trans("supportticketdepts.mailproviderstandard") : $providerName;
    echo "                            </a>\n                            </li>\n                        ";
}
echo "                    </ul>\n                </td>\n            </tr>\n            <tr>\n                <td class=\"fieldlabel\">";
echo AdminLang::trans("fields.hostname");
echo "</td>\n                <td class=\"fieldarea\"><input type=\"text\" name=\"host\" value=\"";
echo $data["host"];
echo "\"\n                                             placeholder=\"mail.example.com\" class=\"form-control input-400\"></td>\n            </tr>\n            <tr>\n                <td class=\"fieldlabel\">";
echo AdminLang::trans("supportticketdepts.pop3port");
echo "</td>\n                <td class=\"fieldarea\"><input type=\"text\" name=\"port\" value=\"";
echo $data["port"];
echo "\" placeholder=\"995\"\n                                             class=\"form-control input-150\"></td>\n            </tr>\n            <tr style=\"display: none\">\n                <td width=\"175px\" class=\"fieldlabel\">";
echo AdminLang::trans("mail.authentication");
echo "</td>\n                <td class=\"fieldarea\">\n                    <select name=\"auth_type\" class=\"form-control input-150\" style=\"display: inline\">\n                        <option value=\"";
echo WHMCS\Mail\MailAuthHandler::AUTH_TYPE_PLAIN;
echo "\" ";
echo $data["auth_type"] === WHMCS\Mail\MailAuthHandler::AUTH_TYPE_PLAIN ? "selected" : "";
echo ">Password</option>\n                        <option value=\"";
echo WHMCS\Mail\MailAuthHandler::AUTH_TYPE_OAUTH2;
echo "\" ";
echo $data["auth_type"] === WHMCS\Mail\MailAuthHandler::AUTH_TYPE_OAUTH2 ? "selected" : "";
echo ">OAuth2</option>\n                    </select>\n                </td>\n            </tr>\n            <tr>\n                <td class=\"fieldlabel\">";
echo AdminLang::trans("supportticketdepts.pop3user");
echo "</td>\n                <td class=\"fieldarea\"><input type=\"text\" name=\"login\" value=\"";
echo $data["login"];
echo "\"\n                                             class=\"form-control input-400\"></td>\n            </tr>\n            <tr style=\"display: none\">\n                <td class=\"fieldlabel\">";
echo AdminLang::trans("mail.oauth2.callback_url");
echo "</td>\n                <td class=\"fieldarea\">\n                    <div class=\"input-group input-400\">\n                        <input type=\"text\" id=\"smtpOauth2CallbackUrl\" name=\"oauth2_callback_url\"\n                               class=\"form-control input-inline\" readonly\n                               value=\"";
echo App::getSystemURL() ? fqdnRoutePath("admin-setup-support-oauth2-callback") : "";
echo "\">\n\n                        <span class=\"input-group-btn\"><button class=\"btn btn-default copy-to-clipboard\"\n                                                              data-clipboard-target=\"#smtpOauth2CallbackUrl\" type=\"button\">\n                                <img src=\"../assets/img/clippy.svg\" alt=\"Copy to clipboard\" width=\"15\">\n                            </button></span>\n                    </div>\n                </td>\n            </tr>\n            <tr style=\"display: none\">\n                <td class=\"fieldlabel\" data-generic-field-label=\"";
echo AdminLang::trans("fields.clientid");
echo "\" data-microsoft-field-label=\"";
echo AdminLang::trans("fields.microsoftappid");
echo "\">";
echo AdminLang::trans("fields.clientid");
echo "</td>\n                <td class=\"fieldarea\"><input type=\"text\" name=\"oauth2_client_id\" class=\"form-control input-400\"\n                                             value=\"";
echo $data["oauth2_client_id"];
echo "\"></td>\n            </tr>\n            <tr style=\"display: none\">\n                <td class=\"fieldlabel\">";
echo AdminLang::trans("fields.clientsecret");
echo "</td>\n                <td class=\"fieldarea\"><input type=\"password\" name=\"oauth2_client_secret\" class=\"form-control input-400\"\n                                             value=\"";
echo replacePasswordWithMasks($data["oauth2_client_secret"]);
echo "\"></td>\n            </tr>\n            <tr style=\"display: none\">\n                <td class=\"fieldlabel\">";
echo AdminLang::trans("fields.connectiontoken");
echo "</td>\n                <td class=\"fieldarea\">\n                    <input type=\"password\" name=\"oauth2_refresh_token\" class=\"form-control input-400\"\n                           value=\"";
echo replacePasswordWithMasks($data["oauth2_refresh_token"]);
echo "\" readonly>\n                </td>\n            </tr>\n\n            <tr>\n                <td class=\"fieldlabel\">";
echo AdminLang::trans("supportticketdepts.pop3pass");
echo "</td>\n                <td class=\"fieldarea\"><input type=\"password\" name=\"password\"\n                                             value=\"";
echo replacePasswordWithMasks($data["password"]);
echo "\" autocomplete=\"off\"\n                                             class=\"form-control input-400\"></td>\n            </tr>\n\n            <tr>\n                <td class=\"fieldlabel\">&nbsp;</td>\n                <td class=\"fieldarea\">\n                    <button id=\"btnConfigureOauth2\" class=\"btn btn-default\" type=\"button\"\n                            style=\"display: none\"\n                            data-role=\"auth-type-element\"\n                            data-auth-type=\"";
echo WHMCS\Mail\MailAuthHandler::AUTH_TYPE_OAUTH2;
echo "\">\n                        ";
echo AdminLang::trans("global.connect");
echo "                    </button>\n                    <button id=\"btnTestMailConnection\" class=\"btn btn-default\" type=\"button\">\n                        <i class=\"fa fa-spinner fa-spin\" style=\"display: none\"></i>\n                        <span>\n                            ";
echo AdminLang::trans("supportticketdepts.pop3testconfiguration");
echo "                        </span>\n                    </button>\n                </td>\n            </tr>\n\n        </table>\n    </div>\n    <div class=\"col-md-4 col-lg-3\" id=\"colOauthHelp\" style=\"padding: 1em; display: none\">\n        ";
foreach (array_keys(WHMCS\Mail\MailAuthHandler::PROVIDER_CLASSES) as $providerName) {
    echo "            <div data-role=\"oauth-provider-instructions\" data-provider=\"";
    echo $providerName;
    echo "\" style=\"display: none\">\n                ";
    echo AdminLang::trans("supportticketdepts.pop3oauthsetupinstructions." . $providerName);
    echo "            </div>\n        ";
}
echo "    </div>\n</div>\n<br><br>\n\n";

?>