<?php

echo "<script>\n    jQuery(document).ready(function() {\n        var csrfToken = '";
echo generate_token("plain");
echo "';\n        var successDiv = jQuery('#mailProviderSuccess');\n\n        var findConfigField = function (fieldName) {\n            return jQuery('#frmMailProviderConfiguration')\n                .find('input[name=\"' + fieldName + '\"],select[name=\"' + fieldName + '\"]')\n                .first();\n        };\n\n        var updateDialogButtons = function(forceState) {\n            var submitButton = jQuery('#btnSaveMailConfiguration');\n            var testButton = jQuery('#btnTestConfiguration');\n            var oauthTokenField = jQuery('#oauth2RefreshToken');\n            var doEnable = true;\n\n            if (typeof forceState === 'boolean') {\n                doEnable = forceState;\n            } else {\n                if (oauthTokenField.is(':visible')) {\n                    if (oauthTokenField.val() === '') {\n                        doEnable = false;\n                    }\n                }\n            }\n\n            if (doEnable) {\n                submitButton.removeClass('disabled').prop('disabled', false);\n                testButton.removeClass('disabled').prop('disabled', false);\n                jQuery(submitButton).removeAttr('data-invalid-config');\n            } else {\n                submitButton.addClass('disabled').prop('disabled', true);\n                testButton.addClass('disabled').prop('disabled', true);\n                jQuery(submitButton).attr('data-invalid-config', true);\n            }\n        };\n\n        var refreshTokenField = findConfigField('oauth2_refresh_token');\n        var refreshTokenFieldParent = refreshTokenField.parent();\n        var serviceProviderSelect = findConfigField('service_provider');\n        var authTypeSelect = findConfigField('auth_type');\n\n        refreshTokenField.attr('id', 'oauth2RefreshToken').remove();\n\n        serviceProviderSelect.attr('id', 'smtpServiceProviderSelect');\n        authTypeSelect.attr('id', 'smtpAuthTypeSelect');\n\n        refreshTokenFieldParent.append(\n            jQuery('<div class=\"input-group\">')\n                .append(\n                    refreshTokenField\n                )\n                .append(\n                    '<span class=\"input-group-btn\">'\n                    + '<button id=\"btnConfigureOauth2\" class=\"btn btn-default\" type=\"button\">'\n                    + '";
echo AdminLang::trans("global.connect");
echo "'\n                    + '</button>'\n                    + '</span>'\n                )\n        );\n\n        jQuery(document).off('click', '#btnConfigureOauth2');\n        jQuery(document).on('click', '#btnConfigureOauth2', function() {\n            var errorDiv = jQuery('#mailProviderError'),\n                self = jQuery(this);\n\n            self.addClass('disabled').prop('disabled', true);\n\n            successDiv.hide();\n\n            WHMCS.http.jqClient.jsonPost(\n                {\n                    url: '";
echo routePath("admin-setup-mail-provider-oauth2-get-auth-url");
echo "',\n                    data: {\n                        target: 'MicrosoftGraph',\n                        serviceProvider: '";
echo WHMCS\Mail\MailAuthHandler::PROVIDER_MICROSOFT;
echo "',\n                        clientId: findConfigField('oauth2_client_id').val(),\n                        clientSecret: findConfigField('oauth2_client_secret').val(),\n                        token: csrfToken\n                    },\n                    success: function(data) {\n                        var popupOptions = {\n                            width: 500,\n                            height: 700\n                        };\n\n                        popupOptions.left = Math.round((screen.availWidth - popupOptions.width) / 2);\n                        popupOptions.top = Math.round((screen.availHeight - popupOptions.height) / 2);\n\n                        var optionsString = Object.keys(popupOptions).map(function (item) {\n                            return item + '=' + popupOptions[item];\n                        }).join(',');\n\n                        window.open(data.url, 'mailOauth2Popup', optionsString);\n\n                    },\n                    error: function(error) {\n                        errorDiv.text(error).show();\n                    },\n                    fail: function(error, xhr) {\n                        errorDiv.text(xhr.responseJSON.errorMessage).show();\n                    },\n                    always: function() {\n                        self.removeClass('disabled').prop('disabled', false);\n                    }\n                }\n            );\n        });\n\n        window.whmcsSetOauthRefreshToken = function(refreshToken) {\n            refreshTokenField.val(refreshToken);\n\n            successDiv\n                .text('";
echo AdminLang::trans("mail.connectionTokenSuccess");
echo "')\n                .show();\n\n            updateDialogButtons();\n        };\n\n        updateDialogButtons();\n    });\n</script>\n";

?>